/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quick.start

data class Vegetable(val name: String, val age: Int, val countryOrigin:String){
}

fun main() {
    println("Hello, World!")
}